akkusativ.artikel = {
  bestimmter: [{
    nummer: SIN,
    genus: MAS,
    value: 'den'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'die'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'das'
  }, {
    nummer: PLU,
    genus: null,
    value: 'die'
  }],
  unbestimmter: [{
    nummer: SIN,
    genus: MAS,
    value: 'einen'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'eine'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'ein'
  }, {
    nummer: PLU,
    genus: null,
    value: '-'
  }]
};

akkusativ.pronomen = {
  personal: [{
    nummer: SIN,
    genus: null,
    value: 'mich'
  }, {
    nummer: SIN,
    genus: null,
    value: 'dich'
  }, {
    nummer: SIN,
    genus: null,
    value: 'Sie'
  }, {
    nummer: SIN,
    genus: MAS,
    value: 'ihn'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'sie'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'es'
  }, {
    nummer: PLU,
    genus: null,
    value: 'uns'
  }, {
    nummer: PLU,
    genus: null,
    value: 'euch'
  }, {
    nummer: PLU,
    genus: null,
    value: 'Sie'
  }, {
    nummer: PLU,
    genus: null,
    value: 'sie'
  }],
  possessiv: [{
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'meinen'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'meine'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'mein'
    }, {
      genus: null,
      nummer: PLU,
      value: 'meine'
    }],
    nummer: SIN,
    genus: null,
    value: 'mein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'deinen'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'deine'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'dein'
    }, {
      genus: null,
      nummer: PLU,
      value: 'deine'
    }],
    nummer: SIN,
    genus: null,
    value: 'dein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'Ihren'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'Ihre'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'Ihr'
    }, {
      genus: null,
      nummer: PLU,
      value: 'Ihre'
    }],
    nummer: SIN,
    genus: null,
    value: 'Ihren'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'seinen'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'seine'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'sein'
    }, {
      genus: null,
      nummer: PLU,
      value: 'seine'
    }],
    nummer: SIN,
    genus: MAS,
    value: 'sein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'Ihren'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'Ihre'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'Ihr'
    }, {
      genus: null,
      nummer: PLU,
      value: 'Ihre'
    }],
    nummer: SIN,
    genus: FEM,
    value: 'ihr'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'seinen'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'seine'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'sein'
    }, {
      genus: null,
      nummer: PLU,
      value: 'seine'
    }],
    nummer: SIN,
    genus: NEU,
    value: 'sein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'unseren'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'unsere'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'unser'
    }, {
      genus: null,
      nummer: PLU,
      value: 'unsere'
    }],
    nummer: PLU,
    genus: null,
    value: 'unser'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'euren'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'euer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'eure'
    }, {
      genus: null,
      nummer: PLU,
      value: 'eure'
    }],
    nummer: PLU,
    genus: null,
    value: 'euer'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'Ihren'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'Ihre'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'Ihr'
    }, {
      genus: null,
      nummer: PLU,
      value: 'Ihre'
    }],
    nummer: PLU,
    genus: null,
    value: 'Ihr'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'ihren'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'ihre'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'ihr'
    }, {
      genus: null,
      nummer: PLU,
      value: 'ihre'
    }],
    nummer: PLU,
    genus: null,
    value: 'ihr'
  }],
  reflexiv: [{
    nummer: SIN,
    genus: null,
    value: 'mich'
  }, {
    nummer: SIN,
    genus: null,
    value: 'dich'
  }, {
    nummer: SIN,
    genus: null,
    value: 'Sich'
  }, {
    nummer: SIN,
    genus: MAS,
    value: 'sich'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'sich'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'sich'
  }, {
    nummer: PLU,
    genus: null,
    value: 'uns'
  }, {
    nummer: PLU,
    genus: null,
    value: 'euch'
  }, {
    nummer: PLU,
    genus: null,
    value: 'Sich'
  }, {
    nummer: PLU,
    genus: null,
    value: 'sich'
  }],
  relativ: [{
    nummer: SIN,
    genus: MAS,
    value: 'den'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'die'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'das'
  }, {
    nummer: PLU,
    genus: null,
    value: 'die'
  }]
};
