dativ.artikel = {
  bestimmter: [{
    nummer: SIN,
    genus: MAS,
    value: 'dem'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'der'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'dem'
  }, {
    nummer: PLU,
    genus: null,
    value: 'den'
  }],
  unbestimmter: [{
    nummer: SIN,
    genus: MAS,
    value: 'einem'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'einer'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'einem'
  }, {
    nummer: PLU,
    genus: null,
    value: '-'
  }]
};

dativ.pronomen = {
  personal: [{
    nummer: SIN,
    genus: null,
    value: 'mir'
  }, {
    nummer: SIN,
    genus: null,
    value: 'dir'
  }, {
    nummer: SIN,
    genus: null,
    value: 'Ihnen'
  }, {
    nummer: SIN,
    genus: MAS,
    value: 'ihm'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'ihr'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'ihm'
  }, {
    nummer: PLU,
    genus: null,
    value: 'uns'
  }, {
    nummer: PLU,
    genus: null,
    value: 'euch'
  }, {
    nummer: PLU,
    genus: null,
    value: 'Ihnen'
  }, {
    nummer: PLU,
    genus: null,
    value: 'ihnen'
  }],
  possessiv: [{
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'meinem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'meiner'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'meinem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'meinen'
    }],
    nummer: SIN,
    genus: null,
    value: 'mein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'deinem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'deiner'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'deinem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'deinen'
    }],
    nummer: SIN,
    genus: null,
    value: 'dein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'Ihrem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'Ihrer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'Ihrem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'Ihren'
    }],
    nummer: SIN,
    genus: null,
    value: 'Ihnen'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'seinem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'seiner'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'seinem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'seinen'
    }],
    nummer: SIN,
    genus: MAS,
    value: 'sein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'ihrem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'ihrer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'ihrem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'ihren'
    }],
    nummer: SIN,
    genus: FEM,
    value: 'ihr'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'seinem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'seiner'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'seinem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'seinen'
    }],
    nummer: SIN,
    genus: NEU,
    value: 'sein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'unserem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'unserer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'unserem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'unseren'
    }],
    nummer: PLU,
    genus: null,
    value: 'unser'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'eurem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'eurer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'eurem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'euren'
    }],
    nummer: PLU,
    genus: null,
    value: 'euer'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'Ihrem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'Ihrer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'Ihrem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'Ihren'
    }],
    nummer: PLU,
    genus: null,
    value: 'Ihr'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'ihrem'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'ihrer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'ihrem'
    }, {
      genus: null,
      nummer: PLU,
      value: 'ihren'
    }],
    nummer: PLU,
    genus: null,
    value: 'ihr'
  }],
  reflexiv: [{
    nummer: SIN,
    genus: null,
    value: 'mir'
  }, {
    nummer: SIN,
    genus: null,
    value: 'dir'
  }, {
    nummer: SIN,
    genus: null,
    value: 'Sich'
  }, {
    nummer: SIN,
    genus: MAS,
    value: 'sich'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'sich'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'sich'
  }, {
    nummer: PLU,
    genus: null,
    value: 'uns'
  }, {
    nummer: PLU,
    genus: null,
    value: 'euch'
  }, {
    nummer: PLU,
    genus: null,
    value: 'Sich'
  }, {
    nummer: PLU,
    genus: null,
    value: 'sich'
  }],
  relativ: [{
    nummer: SIN,
    genus: MAS,
    value: 'dem'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'der'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'dem'
  }, {
    nummer: PLU,
    genus: null,
    value: 'denen'
  }]
};
