dativ.pronomen = {
  reflexiv: [{
    nummer: SIN,
    genus: null,
    value: 'mir'
  }, {
    nummer: SIN,
    genus: null,
    value: 'dir'
  }, {
    nummer: SIN,
    genus: null,
    value: 'Sich'
  }, {
    nummer: SIN,
    genus: MAS,
    value: 'sich'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'sich'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'sich'
  }, {
    nummer: PLU,
    genus: null,
    value: 'uns'
  }, {
    nummer: PLU,
    genus: null,
    value: 'euch'
  }, {
    nummer: PLU,
    genus: null,
    value: 'Sich'
  }, {
    nummer: PLU,
    genus: null,
    value: 'sich'
  }]
};
