genitiv.adjektiv = {
  bestimmter: [{
    nummer: SIN,
    genus: MAS,
    value: '-en'
  }, {
    nummer: SIN,
    genus: FEM,
    value: '-en'
  }, {
    nummer: SIN,
    genus: NEU,
    value: '-en'
  }, {
    nummer: PLU,
    genus: null,
    value: '-en'
  }],
  unbestimmter: [{
    nummer: SIN,
    genus: MAS,
    value: '-en'
  }, {
    nummer: SIN,
    genus: FEM,
    value: '-en'
  }, {
    nummer: SIN,
    genus: NEU,
    value: '-en'
  }, {
    nummer: PLU,
    genus: null,
    value: '-en'
  }],
  ohne: [{
    nummer: SIN,
    genus: MAS,
    value: '-en'
  }, {
    nummer: SIN,
    genus: FEM,
    value: '-er'
  }, {
    nummer: SIN,
    genus: NEU,
    value: '-en'
  }, {
    nummer: PLU,
    genus: null,
    value: '-er'
  }]
};

genitiv.artikel = {
  bestimmter: [{
    nummer: SIN,
    genus: MAS,
    value: 'dem'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'der'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'dem'
  }, {
    nummer: PLU,
    genus: null,
    value: 'den'
  }],
  unbestimmter: [{
    nummer: SIN,
    genus: MAS,
    value: 'einem'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'einer'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'einem'
  }, {
    nummer: PLU,
    genus: null,
    value: '-'
  }]
};

genitiv.pronomen = {
  personal: [{
    nummer: SIN,
    genus: null,
    value: 'mein'
  }, {
    nummer: SIN,
    genus: null,
    value: 'dein'
  }, {
    nummer: SIN,
    genus: null,
    value: 'Ihr'
  }, {
    nummer: SIN,
    genus: MAS,
    value: 'sein'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'ihr'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'sein'
  }, {
    nummer: PLU,
    genus: null,
    value: 'uns'
  }, {
    nummer: PLU,
    genus: null,
    value: 'euer'
  }, {
    nummer: PLU,
    genus: null,
    value: 'Ihr'
  }, {
    nummer: PLU,
    genus: null,
    value: 'ihr'
  }],
  possessiv: [{
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'meines'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'meiner'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'meines'
    }, {
      genus: null,
      nummer: PLU,
      value: 'meiner'
    }],
    nummer: SIN,
    genus: null,
    value: 'mein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'deines'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'deiner'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'deines'
    }, {
      genus: null,
      nummer: PLU,
      value: 'deiner'
    }],
    nummer: SIN,
    genus: null,
    value: 'dein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'Ihres'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'Ihrer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'Ihres'
    }, {
      genus: null,
      nummer: PLU,
      value: 'Ihrer'
    }],
    nummer: SIN,
    genus: null,
    value: 'Ihr'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'seines'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'seiner'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'seines'
    }, {
      genus: null,
      nummer: PLU,
      value: 'seiner'
    }],
    nummer: SIN,
    genus: MAS,
    value: 'sein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'ihres'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'ihrer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'ihres'
    }, {
      genus: null,
      nummer: PLU,
      value: 'ihrer'
    }],
    nummer: SIN,
    genus: FEM,
    value: 'ihr'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'seines'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'seiner'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'seines'
    }, {
      genus: null,
      nummer: PLU,
      value: 'seiner'
    }],
    nummer: SIN,
    genus: NEU,
    value: 'sein'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'unseres'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'unserer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'unseres'
    }, {
      genus: null,
      nummer: PLU,
      value: 'unserer'
    }],
    nummer: PLU,
    genus: null,
    value: 'unser'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'eures'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'eurer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'eures'
    }, {
      genus: null,
      nummer: PLU,
      value: 'eurer'
    }],
    nummer: PLU,
    genus: null,
    value: 'euer'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'Ihres'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'Ihrer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'Ihres'
    }, {
      genus: null,
      nummer: PLU,
      value: 'Ihrer'
    }],
    nummer: PLU,
    genus: null,
    value: 'Ihr'
  }, {
    deklination: [{
      genus: MAS,
      nummer: SIN,
      value: 'ihres'
    }, {
      genus: FEM,
      nummer: SIN,
      value: 'ihrer'
    }, {
      genus: NEU,
      nummer: SIN,
      value: 'ihres'
    }, {
      genus: null,
      nummer: PLU,
      value: 'ihres'
    }],
    nummer: PLU,
    genus: null,
    value: 'ihr'
  }],
  relativ: [{
    nummer: SIN,
    genus: MAS,
    value: 'dessen'
  }, {
    nummer: SIN,
    genus: FEM,
    value: 'deren'
  }, {
    nummer: SIN,
    genus: NEU,
    value: 'dessen'
  }, {
    nummer: PLU,
    genus: null,
    value: 'deren'
  }]
};
